/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.crud.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Games service. Represents a row in the &quot;Sports_Games&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demo.crud.model.impl.GamesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demo.crud.model.impl.GamesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Games
 * @generated
 */
@ProviderType
public interface GamesModel extends BaseModel<Games> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a games model instance should use the {@link Games} interface instead.
	 */

	/**
	 * Returns the primary key of this games.
	 *
	 * @return the primary key of this games
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this games.
	 *
	 * @param primaryKey the primary key of this games
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this games.
	 *
	 * @return the uuid of this games
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this games.
	 *
	 * @param uuid the uuid of this games
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the games ID of this games.
	 *
	 * @return the games ID of this games
	 */
	public long getGamesId();

	/**
	 * Sets the games ID of this games.
	 *
	 * @param gamesId the games ID of this games
	 */
	public void setGamesId(long gamesId);

	/**
	 * Returns the game rules of this games.
	 *
	 * @return the game rules of this games
	 */
	@AutoEscape
	public String getGameRules();

	/**
	 * Sets the game rules of this games.
	 *
	 * @param gameRules the game rules of this games
	 */
	public void setGameRules(String gameRules);

	/**
	 * Returns the game members of this games.
	 *
	 * @return the game members of this games
	 */
	public int getGameMembers();

	/**
	 * Sets the game members of this games.
	 *
	 * @param gameMembers the game members of this games
	 */
	public void setGameMembers(int gameMembers);

	/**
	 * Returns the description of this games.
	 *
	 * @return the description of this games
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this games.
	 *
	 * @param Description the description of this games
	 */
	public void setDescription(String Description);

	/**
	 * Returns the sports ID of this games.
	 *
	 * @return the sports ID of this games
	 */
	public long getSportsId();

	/**
	 * Sets the sports ID of this games.
	 *
	 * @param sportsId the sports ID of this games
	 */
	public void setSportsId(long sportsId);

	/**
	 * Returns the players ID of this games.
	 *
	 * @return the players ID of this games
	 */
	public long getPlayersId();

	/**
	 * Sets the players ID of this games.
	 *
	 * @param playersId the players ID of this games
	 */
	public void setPlayersId(long playersId);

	@Override
	public Games cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}