/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.crud.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Sports service. Represents a row in the &quot;Sports_Sports&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demo.crud.model.impl.SportsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demo.crud.model.impl.SportsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Sports
 * @generated
 */
@ProviderType
public interface SportsModel extends BaseModel<Sports> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sports model instance should use the {@link Sports} interface instead.
	 */

	/**
	 * Returns the primary key of this sports.
	 *
	 * @return the primary key of this sports
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sports.
	 *
	 * @param primaryKey the primary key of this sports
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sports.
	 *
	 * @return the uuid of this sports
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this sports.
	 *
	 * @param uuid the uuid of this sports
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the sports ID of this sports.
	 *
	 * @return the sports ID of this sports
	 */
	public long getSportsId();

	/**
	 * Sets the sports ID of this sports.
	 *
	 * @param sportsId the sports ID of this sports
	 */
	public void setSportsId(long sportsId);

	/**
	 * Returns the sports name of this sports.
	 *
	 * @return the sports name of this sports
	 */
	@AutoEscape
	public String getSportsName();

	/**
	 * Sets the sports name of this sports.
	 *
	 * @param sportsName the sports name of this sports
	 */
	public void setSportsName(String sportsName);

	/**
	 * Returns the description of this sports.
	 *
	 * @return the description of this sports
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this sports.
	 *
	 * @param description the description of this sports
	 */
	public void setDescription(String description);

	@Override
	public Sports cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}