/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.exter.model.impl;

import com.exter.model.Application;
import com.exter.service.ApplicationLocalServiceUtil;

/**
 * The extended model base implementation for the Application service. Represents a row in the &quot;application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationImpl
 * @see Application
 * @generated
 */
public abstract class ApplicationBaseImpl
	extends ApplicationModelImpl implements Application {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application model instance should use the <code>Application</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ApplicationLocalServiceUtil.addApplication(this);
		}
		else {
			ApplicationLocalServiceUtil.updateApplication(this);
		}
	}

}