/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.exter.model.impl;

import com.exter.model.Vlog;
import com.exter.model.VlogModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Vlog service. Represents a row in the &quot;vlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VlogModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VlogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VlogImpl
 * @generated
 */
public class VlogModelImpl extends BaseModelImpl<Vlog> implements VlogModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vlog model instance should use the <code>Vlog</code> interface instead.
	 */
	public static final String TABLE_NAME = "vlog";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"vlogId", Types.BIGINT},
		{"vlogName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vlogId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vlogName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table vlog (uuid_ VARCHAR(75) null,vlogId LONG not null primary key,vlogName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table vlog";

	public static final String ORDER_BY_JPQL = " ORDER BY vlog.vlogId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY vlog.vlogId ASC";

	public static final String DATA_SOURCE = "extDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VLOGID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public VlogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _vlogId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVlogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _vlogId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Vlog.class;
	}

	@Override
	public String getModelClassName() {
		return Vlog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Vlog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Vlog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vlog, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Vlog)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Vlog, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Vlog, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Vlog)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Vlog, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Vlog, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Vlog, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Vlog, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Vlog, Object>>();

			attributeGetterFunctions.put("uuid", Vlog::getUuid);
			attributeGetterFunctions.put("vlogId", Vlog::getVlogId);
			attributeGetterFunctions.put("vlogName", Vlog::getVlogName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Vlog, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Vlog, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Vlog, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Vlog, String>)Vlog::setUuid);
			attributeSetterBiConsumers.put(
				"vlogId", (BiConsumer<Vlog, Long>)Vlog::setVlogId);
			attributeSetterBiConsumers.put(
				"vlogName", (BiConsumer<Vlog, String>)Vlog::setVlogName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getVlogId() {
		return _vlogId;
	}

	@Override
	public void setVlogId(long vlogId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vlogId = vlogId;
	}

	@Override
	public String getVlogName() {
		if (_vlogName == null) {
			return "";
		}
		else {
			return _vlogName;
		}
	}

	@Override
	public void setVlogName(String vlogName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vlogName = vlogName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Vlog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Vlog toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Vlog>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VlogImpl vlogImpl = new VlogImpl();

		vlogImpl.setUuid(getUuid());
		vlogImpl.setVlogId(getVlogId());
		vlogImpl.setVlogName(getVlogName());

		vlogImpl.resetOriginalValues();

		return vlogImpl;
	}

	@Override
	public Vlog cloneWithOriginalValues() {
		VlogImpl vlogImpl = new VlogImpl();

		vlogImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		vlogImpl.setVlogId(this.<Long>getColumnOriginalValue("vlogId"));
		vlogImpl.setVlogName(this.<String>getColumnOriginalValue("vlogName"));

		return vlogImpl;
	}

	@Override
	public int compareTo(Vlog vlog) {
		long primaryKey = vlog.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Vlog)) {
			return false;
		}

		Vlog vlog = (Vlog)object;

		long primaryKey = vlog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Vlog> toCacheModel() {
		VlogCacheModel vlogCacheModel = new VlogCacheModel();

		vlogCacheModel.uuid = getUuid();

		String uuid = vlogCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			vlogCacheModel.uuid = null;
		}

		vlogCacheModel.vlogId = getVlogId();

		vlogCacheModel.vlogName = getVlogName();

		String vlogName = vlogCacheModel.vlogName;

		if ((vlogName != null) && (vlogName.length() == 0)) {
			vlogCacheModel.vlogName = null;
		}

		return vlogCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Vlog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Vlog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vlog, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Vlog)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Vlog>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Vlog.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _vlogId;
	private String _vlogName;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Vlog, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Vlog)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("vlogId", _vlogId);
		_columnOriginalValues.put("vlogName", _vlogName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("vlogId", 2L);

		columnBitmasks.put("vlogName", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Vlog _escapedModel;

}