/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.exter.model.impl;

import com.exter.model.Vlog;
import com.exter.service.VlogLocalServiceUtil;

/**
 * The extended model base implementation for the Vlog service. Represents a row in the &quot;vlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VlogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VlogImpl
 * @see Vlog
 * @generated
 */
public abstract class VlogBaseImpl extends VlogModelImpl implements Vlog {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vlog model instance should use the <code>Vlog</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			VlogLocalServiceUtil.addVlog(this);
		}
		else {
			VlogLocalServiceUtil.updateVlog(this);
		}
	}

}