/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.excel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Hospital service. Represents a row in the &quot;excel_Hospital&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.excel.model.impl.HospitalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.excel.model.impl.HospitalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Hospital
 * @generated
 */
@ProviderType
public interface HospitalModel extends BaseModel<Hospital> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hospital model instance should use the {@link Hospital} interface instead.
	 */

	/**
	 * Returns the primary key of this hospital.
	 *
	 * @return the primary key of this hospital
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hospital.
	 *
	 * @param primaryKey the primary key of this hospital
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this hospital.
	 *
	 * @return the uuid of this hospital
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this hospital.
	 *
	 * @param uuid the uuid of this hospital
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the hospital ID of this hospital.
	 *
	 * @return the hospital ID of this hospital
	 */
	public long getHospitalId();

	/**
	 * Sets the hospital ID of this hospital.
	 *
	 * @param hospitalId the hospital ID of this hospital
	 */
	public void setHospitalId(long hospitalId);

	/**
	 * Returns the hospital name of this hospital.
	 *
	 * @return the hospital name of this hospital
	 */
	@AutoEscape
	public String getHospitalName();

	/**
	 * Sets the hospital name of this hospital.
	 *
	 * @param hospitalName the hospital name of this hospital
	 */
	public void setHospitalName(String hospitalName);

	/**
	 * Returns the hospital address of this hospital.
	 *
	 * @return the hospital address of this hospital
	 */
	@AutoEscape
	public String getHospitalAddress();

	/**
	 * Sets the hospital address of this hospital.
	 *
	 * @param hospitalAddress the hospital address of this hospital
	 */
	public void setHospitalAddress(String hospitalAddress);

	/**
	 * Returns the hospital details of this hospital.
	 *
	 * @return the hospital details of this hospital
	 */
	@AutoEscape
	public String getHospitalDetails();

	/**
	 * Sets the hospital details of this hospital.
	 *
	 * @param hospitalDetails the hospital details of this hospital
	 */
	public void setHospitalDetails(String hospitalDetails);

	@Override
	public Hospital cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}