/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.excel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Players service. Represents a row in the &quot;excel_Players&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.excel.model.impl.PlayersModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.excel.model.impl.PlayersImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Players
 * @generated
 */
@ProviderType
public interface PlayersModel extends BaseModel<Players> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a players model instance should use the {@link Players} interface instead.
	 */

	/**
	 * Returns the primary key of this players.
	 *
	 * @return the primary key of this players
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this players.
	 *
	 * @param primaryKey the primary key of this players
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this players.
	 *
	 * @return the uuid of this players
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this players.
	 *
	 * @param uuid the uuid of this players
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the players ID of this players.
	 *
	 * @return the players ID of this players
	 */
	public long getPlayersId();

	/**
	 * Sets the players ID of this players.
	 *
	 * @param playersId the players ID of this players
	 */
	public void setPlayersId(long playersId);

	/**
	 * Returns the players name of this players.
	 *
	 * @return the players name of this players
	 */
	@AutoEscape
	public String getPlayersName();

	/**
	 * Sets the players name of this players.
	 *
	 * @param playersName the players name of this players
	 */
	public void setPlayersName(String playersName);

	/**
	 * Returns the players age of this players.
	 *
	 * @return the players age of this players
	 */
	public int getPlayersAge();

	/**
	 * Sets the players age of this players.
	 *
	 * @param playersAge the players age of this players
	 */
	public void setPlayersAge(int playersAge);

	/**
	 * Returns the description of this players.
	 *
	 * @return the description of this players
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this players.
	 *
	 * @param Description the description of this players
	 */
	public void setDescription(String Description);

	@Override
	public Players cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}