/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.crud.service.base;

import com.demo.crud.model.Players;
import com.demo.crud.service.PlayersService;
import com.demo.crud.service.PlayersServiceUtil;
import com.demo.crud.service.persistence.GamesPersistence;
import com.demo.crud.service.persistence.PlayersFinder;
import com.demo.crud.service.persistence.PlayersPersistence;
import com.demo.crud.service.persistence.SportsFinder;
import com.demo.crud.service.persistence.SportsPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the players remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.demo.crud.service.impl.PlayersServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.demo.crud.service.impl.PlayersServiceImpl
 * @generated
 */
public abstract class PlayersServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, PlayersService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PlayersService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PlayersServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		PlayersServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PlayersService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		playersService = (PlayersService)aopProxy;

		PlayersServiceUtil.setService(playersService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PlayersService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Players.class;
	}

	protected String getModelClassName() {
		return Players.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = playersPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected GamesPersistence gamesPersistence;

	@Reference
	protected com.demo.crud.service.PlayersLocalService playersLocalService;

	protected PlayersService playersService;

	@Reference
	protected PlayersPersistence playersPersistence;

	@Reference
	protected PlayersFinder playersFinder;

	@Reference
	protected SportsPersistence sportsPersistence;

	@Reference
	protected SportsFinder sportsFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		PlayersServiceBaseImpl.class);

}