/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.exter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Application service. Represents a row in the &quot;application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.exter.model.impl.ApplicationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.exter.model.impl.ApplicationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Application
 * @generated
 */
@ProviderType
public interface ApplicationModel extends BaseModel<Application> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application model instance should use the {@link Application} interface instead.
	 */

	/**
	 * Returns the primary key of this application.
	 *
	 * @return the primary key of this application
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application.
	 *
	 * @param primaryKey the primary key of this application
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this application.
	 *
	 * @return the uuid of this application
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this application.
	 *
	 * @param uuid the uuid of this application
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the app ID of this application.
	 *
	 * @return the app ID of this application
	 */
	public long getAppId();

	/**
	 * Sets the app ID of this application.
	 *
	 * @param appId the app ID of this application
	 */
	public void setAppId(long appId);

	/**
	 * Returns the app name of this application.
	 *
	 * @return the app name of this application
	 */
	@AutoEscape
	public String getAppName();

	/**
	 * Sets the app name of this application.
	 *
	 * @param appName the app name of this application
	 */
	public void setAppName(String appName);

	@Override
	public Application cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}