/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.exter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Vlog service. Represents a row in the &quot;vlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.exter.model.impl.VlogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.exter.model.impl.VlogImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vlog
 * @generated
 */
@ProviderType
public interface VlogModel extends BaseModel<Vlog> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vlog model instance should use the {@link Vlog} interface instead.
	 */

	/**
	 * Returns the primary key of this vlog.
	 *
	 * @return the primary key of this vlog
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vlog.
	 *
	 * @param primaryKey the primary key of this vlog
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this vlog.
	 *
	 * @return the uuid of this vlog
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this vlog.
	 *
	 * @param uuid the uuid of this vlog
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the vlog ID of this vlog.
	 *
	 * @return the vlog ID of this vlog
	 */
	public long getVlogId();

	/**
	 * Sets the vlog ID of this vlog.
	 *
	 * @param vlogId the vlog ID of this vlog
	 */
	public void setVlogId(long vlogId);

	/**
	 * Returns the vlog name of this vlog.
	 *
	 * @return the vlog name of this vlog
	 */
	@AutoEscape
	public String getVlogName();

	/**
	 * Sets the vlog name of this vlog.
	 *
	 * @param vlogName the vlog name of this vlog
	 */
	public void setVlogName(String vlogName);

	@Override
	public Vlog cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}