/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.crud.model.impl;

import com.demo.crud.model.Games;
import com.demo.crud.model.GamesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Games service. Represents a row in the &quot;Sports_Games&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GamesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GamesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GamesImpl
 * @generated
 */
@JSON(strict = true)
public class GamesModelImpl extends BaseModelImpl<Games> implements GamesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a games model instance should use the <code>Games</code> interface instead.
	 */
	public static final String TABLE_NAME = "Sports_Games";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"gamesId", Types.BIGINT},
		{"gamessName", Types.VARCHAR}, {"gamesAge", Types.INTEGER},
		{"Description", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gamesId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("gamessName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gamesAge", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Sports_Games (uuid_ VARCHAR(75) null,gamesId LONG not null primary key,gamessName VARCHAR(75) null,gamesAge INTEGER,Description VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Sports_Games";

	public static final String ORDER_BY_JPQL = " ORDER BY games.gamesId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Sports_Games.gamesId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GAMESID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GamesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _gamesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGamesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _gamesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Games.class;
	}

	@Override
	public String getModelClassName() {
		return Games.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Games, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Games, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Games, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Games)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Games, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Games, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Games)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Games, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Games, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Games, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Games, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Games, Object>>();

			attributeGetterFunctions.put("uuid", Games::getUuid);
			attributeGetterFunctions.put("gamesId", Games::getGamesId);
			attributeGetterFunctions.put("gamessName", Games::getGamessName);
			attributeGetterFunctions.put("gamesAge", Games::getGamesAge);
			attributeGetterFunctions.put("Description", Games::getDescription);
			attributeGetterFunctions.put("groupId", Games::getGroupId);
			attributeGetterFunctions.put("companyId", Games::getCompanyId);
			attributeGetterFunctions.put("userId", Games::getUserId);
			attributeGetterFunctions.put("userName", Games::getUserName);
			attributeGetterFunctions.put("createDate", Games::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Games::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Games, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Games, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Games, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Games, String>)Games::setUuid);
			attributeSetterBiConsumers.put(
				"gamesId", (BiConsumer<Games, Long>)Games::setGamesId);
			attributeSetterBiConsumers.put(
				"gamessName", (BiConsumer<Games, String>)Games::setGamessName);
			attributeSetterBiConsumers.put(
				"gamesAge", (BiConsumer<Games, Integer>)Games::setGamesAge);
			attributeSetterBiConsumers.put(
				"Description",
				(BiConsumer<Games, String>)Games::setDescription);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Games, Long>)Games::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Games, Long>)Games::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Games, Long>)Games::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Games, String>)Games::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Games, Date>)Games::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Games, Date>)Games::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getGamesId() {
		return _gamesId;
	}

	@Override
	public void setGamesId(long gamesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gamesId = gamesId;
	}

	@JSON
	@Override
	public String getGamessName() {
		if (_gamessName == null) {
			return "";
		}
		else {
			return _gamessName;
		}
	}

	@Override
	public void setGamessName(String gamessName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gamessName = gamessName;
	}

	@JSON
	@Override
	public int getGamesAge() {
		return _gamesAge;
	}

	@Override
	public void setGamesAge(int gamesAge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gamesAge = gamesAge;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_Description == null) {
			return "";
		}
		else {
			return _Description;
		}
	}

	@Override
	public void setDescription(String Description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Description = Description;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Games.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Games.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Games toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Games>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GamesImpl gamesImpl = new GamesImpl();

		gamesImpl.setUuid(getUuid());
		gamesImpl.setGamesId(getGamesId());
		gamesImpl.setGamessName(getGamessName());
		gamesImpl.setGamesAge(getGamesAge());
		gamesImpl.setDescription(getDescription());
		gamesImpl.setGroupId(getGroupId());
		gamesImpl.setCompanyId(getCompanyId());
		gamesImpl.setUserId(getUserId());
		gamesImpl.setUserName(getUserName());
		gamesImpl.setCreateDate(getCreateDate());
		gamesImpl.setModifiedDate(getModifiedDate());

		gamesImpl.resetOriginalValues();

		return gamesImpl;
	}

	@Override
	public Games cloneWithOriginalValues() {
		GamesImpl gamesImpl = new GamesImpl();

		gamesImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		gamesImpl.setGamesId(this.<Long>getColumnOriginalValue("gamesId"));
		gamesImpl.setGamessName(
			this.<String>getColumnOriginalValue("gamessName"));
		gamesImpl.setGamesAge(this.<Integer>getColumnOriginalValue("gamesAge"));
		gamesImpl.setDescription(
			this.<String>getColumnOriginalValue("Description"));
		gamesImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		gamesImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		gamesImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		gamesImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		gamesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		gamesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return gamesImpl;
	}

	@Override
	public int compareTo(Games games) {
		long primaryKey = games.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Games)) {
			return false;
		}

		Games games = (Games)object;

		long primaryKey = games.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Games> toCacheModel() {
		GamesCacheModel gamesCacheModel = new GamesCacheModel();

		gamesCacheModel.uuid = getUuid();

		String uuid = gamesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			gamesCacheModel.uuid = null;
		}

		gamesCacheModel.gamesId = getGamesId();

		gamesCacheModel.gamessName = getGamessName();

		String gamessName = gamesCacheModel.gamessName;

		if ((gamessName != null) && (gamessName.length() == 0)) {
			gamesCacheModel.gamessName = null;
		}

		gamesCacheModel.gamesAge = getGamesAge();

		gamesCacheModel.Description = getDescription();

		String Description = gamesCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			gamesCacheModel.Description = null;
		}

		gamesCacheModel.groupId = getGroupId();

		gamesCacheModel.companyId = getCompanyId();

		gamesCacheModel.userId = getUserId();

		gamesCacheModel.userName = getUserName();

		String userName = gamesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			gamesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			gamesCacheModel.createDate = createDate.getTime();
		}
		else {
			gamesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			gamesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			gamesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return gamesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Games, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Games, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Games, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Games)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Games>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Games.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _gamesId;
	private String _gamessName;
	private int _gamesAge;
	private String _Description;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Games, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Games)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("gamesId", _gamesId);
		_columnOriginalValues.put("gamessName", _gamessName);
		_columnOriginalValues.put("gamesAge", _gamesAge);
		_columnOriginalValues.put("Description", _Description);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("gamesId", 2L);

		columnBitmasks.put("gamessName", 4L);

		columnBitmasks.put("gamesAge", 8L);

		columnBitmasks.put("Description", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Games _escapedModel;

}