/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.crud.model.impl;

import com.demo.crud.model.Games;
import com.demo.crud.service.GamesLocalServiceUtil;

/**
 * The extended model base implementation for the Games service. Represents a row in the &quot;Sports_Games&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GamesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GamesImpl
 * @see Games
 * @generated
 */
public abstract class GamesBaseImpl extends GamesModelImpl implements Games {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a games model instance should use the <code>Games</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GamesLocalServiceUtil.addGames(this);
		}
		else {
			GamesLocalServiceUtil.updateGames(this);
		}
	}

}