/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.crud.model.impl;

import com.demo.crud.model.Players;
import com.demo.crud.model.PlayersModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Players service. Represents a row in the &quot;Sports_Players&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PlayersModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlayersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlayersImpl
 * @generated
 */
@JSON(strict = true)
public class PlayersModelImpl
	extends BaseModelImpl<Players> implements PlayersModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a players model instance should use the <code>Players</code> interface instead.
	 */
	public static final String TABLE_NAME = "Sports_Players";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"playersId", Types.BIGINT},
		{"playersName", Types.VARCHAR}, {"playersAge", Types.INTEGER},
		{"Description", Types.VARCHAR}, {"sportsId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("playersId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("playersName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("playersAge", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sportsId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Sports_Players (uuid_ VARCHAR(75) null,playersId LONG not null primary key,playersName VARCHAR(75) null,playersAge INTEGER,Description VARCHAR(75) null,sportsId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Sports_Players";

	public static final String ORDER_BY_JPQL =
		" ORDER BY players.playersId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Sports_Players.playersId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLAYERSID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PlayersModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _playersId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPlayersId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _playersId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Players.class;
	}

	@Override
	public String getModelClassName() {
		return Players.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Players, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Players, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Players, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Players)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Players, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Players, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Players)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Players, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Players, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Players, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Players, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Players, Object>>();

			attributeGetterFunctions.put("uuid", Players::getUuid);
			attributeGetterFunctions.put("playersId", Players::getPlayersId);
			attributeGetterFunctions.put(
				"playersName", Players::getPlayersName);
			attributeGetterFunctions.put("playersAge", Players::getPlayersAge);
			attributeGetterFunctions.put(
				"Description", Players::getDescription);
			attributeGetterFunctions.put("sportsId", Players::getSportsId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Players, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Players, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Players, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Players, String>)Players::setUuid);
			attributeSetterBiConsumers.put(
				"playersId", (BiConsumer<Players, Long>)Players::setPlayersId);
			attributeSetterBiConsumers.put(
				"playersName",
				(BiConsumer<Players, String>)Players::setPlayersName);
			attributeSetterBiConsumers.put(
				"playersAge",
				(BiConsumer<Players, Integer>)Players::setPlayersAge);
			attributeSetterBiConsumers.put(
				"Description",
				(BiConsumer<Players, String>)Players::setDescription);
			attributeSetterBiConsumers.put(
				"sportsId", (BiConsumer<Players, Long>)Players::setSportsId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPlayersId() {
		return _playersId;
	}

	@Override
	public void setPlayersId(long playersId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_playersId = playersId;
	}

	@JSON
	@Override
	public String getPlayersName() {
		if (_playersName == null) {
			return "";
		}
		else {
			return _playersName;
		}
	}

	@Override
	public void setPlayersName(String playersName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_playersName = playersName;
	}

	@JSON
	@Override
	public int getPlayersAge() {
		return _playersAge;
	}

	@Override
	public void setPlayersAge(int playersAge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_playersAge = playersAge;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_Description == null) {
			return "";
		}
		else {
			return _Description;
		}
	}

	@Override
	public void setDescription(String Description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Description = Description;
	}

	@JSON
	@Override
	public long getSportsId() {
		return _sportsId;
	}

	@Override
	public void setSportsId(long sportsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sportsId = sportsId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Players.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Players toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Players>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PlayersImpl playersImpl = new PlayersImpl();

		playersImpl.setUuid(getUuid());
		playersImpl.setPlayersId(getPlayersId());
		playersImpl.setPlayersName(getPlayersName());
		playersImpl.setPlayersAge(getPlayersAge());
		playersImpl.setDescription(getDescription());
		playersImpl.setSportsId(getSportsId());

		playersImpl.resetOriginalValues();

		return playersImpl;
	}

	@Override
	public Players cloneWithOriginalValues() {
		PlayersImpl playersImpl = new PlayersImpl();

		playersImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		playersImpl.setPlayersId(
			this.<Long>getColumnOriginalValue("playersId"));
		playersImpl.setPlayersName(
			this.<String>getColumnOriginalValue("playersName"));
		playersImpl.setPlayersAge(
			this.<Integer>getColumnOriginalValue("playersAge"));
		playersImpl.setDescription(
			this.<String>getColumnOriginalValue("Description"));
		playersImpl.setSportsId(this.<Long>getColumnOriginalValue("sportsId"));

		return playersImpl;
	}

	@Override
	public int compareTo(Players players) {
		long primaryKey = players.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Players)) {
			return false;
		}

		Players players = (Players)object;

		long primaryKey = players.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Players> toCacheModel() {
		PlayersCacheModel playersCacheModel = new PlayersCacheModel();

		playersCacheModel.uuid = getUuid();

		String uuid = playersCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			playersCacheModel.uuid = null;
		}

		playersCacheModel.playersId = getPlayersId();

		playersCacheModel.playersName = getPlayersName();

		String playersName = playersCacheModel.playersName;

		if ((playersName != null) && (playersName.length() == 0)) {
			playersCacheModel.playersName = null;
		}

		playersCacheModel.playersAge = getPlayersAge();

		playersCacheModel.Description = getDescription();

		String Description = playersCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			playersCacheModel.Description = null;
		}

		playersCacheModel.sportsId = getSportsId();

		return playersCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Players, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Players, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Players, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Players)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Players>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Players.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _playersId;
	private String _playersName;
	private int _playersAge;
	private String _Description;
	private long _sportsId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Players, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Players)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("playersId", _playersId);
		_columnOriginalValues.put("playersName", _playersName);
		_columnOriginalValues.put("playersAge", _playersAge);
		_columnOriginalValues.put("Description", _Description);
		_columnOriginalValues.put("sportsId", _sportsId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("playersId", 2L);

		columnBitmasks.put("playersName", 4L);

		columnBitmasks.put("playersAge", 8L);

		columnBitmasks.put("Description", 16L);

		columnBitmasks.put("sportsId", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Players _escapedModel;

}